import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
        <h1 className={styles.title}>
          Michael Jamestong
        </h1>

        <h2 className={styles.description}>
          michael_z96@live.com &diams; (+62) 821-8575-2088 &diams; Jakarta, Indonesia
        </h2>
        </div>

        <hr className={styles.linebreak}>
        </hr>

        <p className={styles.description}>
          Work Experience
        </p>

        <div className={styles.card_container}>
            <div className={styles.card}>
            <h2 className={styles.description}>Customer 360: Partner with PM and Campaign Management Team to provide data to define a customer-focused business decision</h2>
            <ul>
            <li>Managed and led Customer 360 projects to create automation for SQL on multiple datasets with over 30+ tables and 100M+ rows of data, which reduced the time to get the complete information by 95%.</li>
            <li>Identified the opportunity to help business user to manage the contact policy to prevent the occurrence of multiple calls of offers that might annoy the customer by 90%.</li>
            <li>Coordinated with multiple cross-functional teams including Engineer, Product Manager, Vendor Ops, Legal, Sales, and Support to validate the process and information through development and post-implementation.</li>
            </ul>
            </div>

            <div className={styles.card}>
                CARD2
            </div>

            <div className={styles.card}>
                CARD3
            </div>




        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
