  import type { NextPage } from 'next'
  import Head from 'next/head'
  import Image from 'next/image'
  import styles from '../styles/Home.module.css'

  const Home: NextPage = () => {
    return (
      <div className={styles.container}>
        <Head>
          <title>My Resume</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.header}>
          <h1 className={styles.title}>
            Michael Jamestong
          </h1>

          <h2 className={styles.description}>
            michael_z96@live.com &diams; (+62) 821-8575-2088 &diams; Jakarta, Indonesia
          </h2>
          </div>

          <hr className={styles.linebreak}>
          </hr>

          <p className={styles.section}>
            Work Experience
          </p>

          <div className={styles.card_container}>
              <div className={styles.card}>
              <h2 className={styles.description}>Customer 360: Partner with PM and Campaign Management Team to provide data to define a customer-focused business decision</h2>
              <ul>
              <li>Managed and led Customer 360 projects to create automation for SQL on multiple datasets with over 30+ tables and 100M+ rows of data, which reduced the time to get the complete information by 95%.</li>
              <li>Identified the opportunity to help business user to manage the contact policy to prevent the occurrence of multiple calls of offers that might annoy the customer by 90%.</li>
              <li>Coordinated with multiple cross-functional teams including Engineer, Product Manager, Vendor Ops, Legal, Sales, and Support to validate the process and information through development and post-implementation.</li>
              </ul>
              </div>

              <div className={styles.card}>
              <h2 className={styles.description}>Antasena: Partner with the Legal and Business Administration Team to provide the compulsory regulatory report</h2>
              <ul>
              <li>Managed automation process for 2 different reporting formats across different subjects to help the legal team submit the report ahead of schedule by an average of 4 days each month throughout the year.</li>
              </ul>
              <h2 className={styles.description}>Data Migration: Internal projects within the Data Warehouse team to migrate data from Oracle to Big Data</h2>
              <ul>
              <li>Arranged, developed, and implemented over 50+ tables of data from Oracle Database to Hive and Impala-based Big Data Database which saved around 20% of loading time.</li>
              </ul>

              </div>

              <div className={styles.card}>
              <h2 className={styles.description}>Service Quality Improvement: Partner with the internal developer to manage and improve the quality of work</h2>
              <ul>
              <li>Created the framework which helped the developer save time to implement their project and reduce post-implementation errors and bugs by 10% within 3 months.</li>
              <li>Created automation scripts that help the process of migration and overwriting the data for Big Data database saves developers 50% of their time.</li>
              <li>Proactively identified a flawed and abused process within the development phase of a project, which help to prevent the possibility of unauthorized access to data.</li>
              </ul>
              </div>
          </div>

          <p className={styles.section}>
            Education
          </p>

          <div className={styles.round_container}>
            Bina Nusantara<br></br>
            Bachelor of Computer Science<br></br>
            Cumulative GPA :3.58/4.00<br></br>
            Graduated on August 2018<br></br>
            Part of Student Exchange Program to Nottingham University in 2017
          </div>

          <p className={styles.section}>
            Tech Stacks
          </p>

          <div className={styles.tech_container}>
            <div className={styles.icon}>
            <Image src="/git.png"alt="Git Logo" width={100} height={100}/>  
            </div>          
            <div className={styles.icon}>
            <Image src="/infa.png"alt="Infa Logo" width={250} height={100}/>
            </div>
            <div className={styles.icon}>
            <Image src="/sql.png"alt="SQL Logo" width={180} height={100}/>
            </div>
            <div className={styles.icon}>
            <Image src="/python.png"alt="Python Logo" width={200} height={100}/>
            </div>
          </div>

        </main>

      </div>
    )
  }

  export default Home
